### ISSUE TITLE
Crashing on server side. 

### ISSUE THREAD

**Issue by dmodoomsirius** [SE7-KN8/wool#1]
Hello your mod is referencing `MC 18w50a: net/minecraft/client/gui/ContainerGui` when launching on a server. 

https://gist.github.com/dmodoomsirius/42a7ea6b1544a57496c5d438400ebfd2

**Comment by se7kn8** [comment]
Thanks for reporting, I've released a fixed version: [wool-1.1.1.jar](https://minecraft.curseforge.com/projects/wool/files/2654206)
