### ISSUE TITLE
needs updating

### ISSUE THREAD

**Issue by UpcraftLP** [SE7-KN8/wool#2]
wool 1.1.4 does not work on Minecraft 19w07a, due to some changes in the fabric API

**Comment by se7kn8** [comment]
Thanks for the information! I'm currently very busy, so I missed the changes in the fabric API. I will update wool, as soon I have more time.

**Comment by se7kn8** [comment]
Wool should be now compatible with the fabric API. [Here is the new release](https://github.com/SE7-KN8/wool/releases/tag/1.1.5) (Curse is currently processing the file)

**Comment by UpcraftLP** [comment]
nice, thanks ^^
