### ISSUE TITLE
Broken on server

### ISSUE THREAD

**Issue by sargunv** [SE7-KN8/wool#4]
https://github.com/SE7-KN8/wool/blob/1a570b136d62eaf87110aee1b4ff4fffa67f7259/src/main/java/com/github/se7_kn8/wool/Wool.java#L129

This mod crashes at load on the dedicated server, because you're referring to the ClientSidePacketRegistry in the common initialize. Move create a client initializer and move client side registration there to fix it.

**Comment by se7kn8** [comment]
Thanks for the information, I will publish a new version to curse ASAP.

Update: The new version is [available](https://minecraft.curseforge.com/projects/wool/files/2704312).
