### ISSUE TITLE
getting a crash with the Multi Mc build 1.4.1-0.4.7 build  

### ISSUE THREAD

**Issue by Dragonracer1973** [SE7-KN8/wool#9]
[crash-2019-05-14_07.10.34-client.txt](https://github.com/SE7-KN8/wool/files/3177588/crash-2019-05-14_07.10.34-client.txt)

**Comment by se7kn8** [comment]
Wool 1.3.6 is made for 1.14.1. Your crash log says that you are using minecraft 1.14. Please upgrade minecraft to 1.14.1 or use Wool 1.2.6.
